version: '3.8'

services:
  ai-api:
    build: .
    image: sy321/sy_docker:latest
    container_name: ai-model-api-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always


